# 系统信号
set_property PACKAGE_PIN M19 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN L18 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

# 8 LED
set_property PACKAGE_PIN V4 [get_ports {led[0]}]
set_property PACKAGE_PIN U7 [get_ports {led[7]}]
set_property PACKAGE_PIN W5 [get_ports {led[6]}]
set_property PACKAGE_PIN W6 [get_ports {led[5]}]
set_property PACKAGE_PIN W7 [get_ports {led[4]}]
set_property PACKAGE_PIN U6 [get_ports {led[1]}]
set_property PACKAGE_PIN U5 [get_ports {led[2]}]
set_property PACKAGE_PIN V7 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]

# 8个拨码开关
set_property PACKAGE_PIN AB6 [get_ports {switch[0]}]
set_property PACKAGE_PIN Y4 [get_ports {switch[1]}]
set_property PACKAGE_PIN AA4 [get_ports {switch[2]}]
set_property PACKAGE_PIN R6 [get_ports {switch[3]}]
set_property PACKAGE_PIN T6 [get_ports {switch[4]}]
set_property PACKAGE_PIN T4 [get_ports {switch[5]}]
set_property PACKAGE_PIN U4 [get_ports {switch[6]}]
set_property PACKAGE_PIN V5 [get_ports {switch[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]

# 8位数码管
set_property PACKAGE_PIN R21 [get_ports {seg_led1[0]}]
set_property PACKAGE_PIN P20 [get_ports {seg_led1[1]}]
set_property PACKAGE_PIN P21 [get_ports {seg_led1[2]}]
set_property PACKAGE_PIN N15 [get_ports {seg_led1[3]}]
set_property PACKAGE_PIN P15 [get_ports {seg_led1[4]}]
set_property PACKAGE_PIN P17 [get_ports {seg_led1[5]}]
set_property PACKAGE_PIN P18 [get_ports {seg_led1[6]}]
set_property PACKAGE_PIN T16 [get_ports {seg_led1[7]}]
set_property PACKAGE_PIN T17 [get_ports {seg_led2[0]}]
set_property PACKAGE_PIN R19 [get_ports {seg_led2[1]}]
set_property PACKAGE_PIN T19 [get_ports {seg_led2[2]}]
set_property PACKAGE_PIN R18 [get_ports {seg_led2[3]}]
set_property PACKAGE_PIN T18 [get_ports {seg_led2[4]}]
set_property PACKAGE_PIN P16 [get_ports {seg_led2[5]}]
set_property PACKAGE_PIN R16 [get_ports {seg_led2[6]}]
set_property PACKAGE_PIN R15 [get_ports {seg_led2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[7]}]
set_property PACKAGE_PIN M20 [get_ports {tube_en[0]}]
set_property PACKAGE_PIN N19 [get_ports {tube_en[1]}]
set_property PACKAGE_PIN N20 [get_ports {tube_en[2]}]
set_property PACKAGE_PIN M21 [get_ports {tube_en[3]}]
set_property PACKAGE_PIN M22 [get_ports {tube_en[4]}]
set_property PACKAGE_PIN N22 [get_ports {tube_en[5]}]
set_property PACKAGE_PIN P22 [get_ports {tube_en[6]}]
set_property PACKAGE_PIN R20 [get_ports {tube_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_en[7]}]

# UART
set_property PACKAGE_PIN T21 [get_ports uart_rxd]
set_property PACKAGE_PIN T22 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]


set_property IOSTANDARD LVCMOS33 [get_ports bt_rx]
set_property IOSTANDARD LVCMOS33 [get_ports bt_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN AA13 [get_ports bt_tx]
set_property PACKAGE_PIN T21 [get_ports uart_rx]
set_property PACKAGE_PIN T22 [get_ports uart_tx]
set_property PACKAGE_PIN Y13 [get_ports bt_rx]
