# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.cache/wt [current_project]
set_property parent.project_path F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/para.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/cpu/ALU.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/BUS.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/Buffer.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/cpu/CMP.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/cpu/EX.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/cpu/ID.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/cpu/IF.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/Inctrl_led.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/Inctrl_tube.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/OutCtrl_Switch.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/RAM.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/cpu/REG.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/ROM.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/Switch.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/Timer.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/UART.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/cpu/WB.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/counter.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/cpu/cpu.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/cpu/crtl.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/deviceclk.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/digit_tube.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/led.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/uart_recv.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/bus/uart_send.v
  F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/top.v
}
read_ip -quiet F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/ip/data_mem/data_mem.xci
set_property used_in_implementation false [get_files -all f:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/ip/data_mem/data_mem_ooc.xdc]

read_ip -quiet F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/ip/inst_mem/inst_mem.xci
set_property used_in_implementation false [get_files -all f:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/sources_1/ip/inst_mem/inst_mem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files F:/Study/digit_circuit/cpu_design/cpu6_7/cpu6_7.srcs/constrs_1/new/xdc.xdc]


synth_design -top top -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
